language: python
sudo: required
dist: trusty

python:
  - "3.6"
    
before_install:
  - apt-get install samtools tabix -y
  - chmod +x ../.travis/run.sh
  - chmod +x ../.travis/install.sh

install:
- "./.travis/install.sh"

script: 
- "./.travis/run.sh"
